In [1]:
import pandas as pd

In [2]:
file_path = "/workspaces/tir102_data-pipeline/resource/Holding data.csv"
df = pd.read_csv(file_path, nrows=1000000)

In [3]:
df.groupby("portno") #do nothing only show memory location

In [4]:
df.groupby("portno").size()

portno
2998623    351
2998638     77
2998809     70
2998821     54
2999052      2
          ...
309260a      2
309260d    514
3092616      1
3092619    403
3092652     27
Length: 3867, dtype: int64

In [7]:
# df[df["portno" == "2999052"]]
df.groupby("portno").get_group("2999052")

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
552,2999052,2020/10/31,282,2021/01/08,0.05,525000.0,525071.74,Hewlett Packard Enterprise Co .954% 05-OCT-2021,42824CBB
553,2999052,2020/10/31,352,2021/01/08,0.03,335000.0,330737.56,Ford Motor Credit Company LLC 1.044% 05-APR-2021,345397YY

In [8]:
"""
select
    portno,
    perent_tna,
    count(1)
from table
group by portno, percent_tna
"""
df.groupby(["portno", "percent_tna"]).size()

portno   percent_tna
2998623  -0.34           1
         -0.17           1
         -0.02           1
          0.00          19
          0.01           8
                        ..
3092652   0.61           3
          0.62           1
          0.63           1
          3.01           1
          101.93         1
Length: 184136, dtype: int64

In [10]:
df.groupby(["percent_tna", "portno"]).size() #groupby有順序性

percent_tna  portno
-200.00      3086562    1
-199.90      3086604    1
-197.20      3087462    1
-176.40      307545c    1
-173.40      3069606    1
                       ..
 299.85      3086556    1
 299.94      3086604    1
 300.01      3086607    1
 300.04      3086562    1
 300.08      308655c    1
Length: 184136, dtype: int64

In [17]:
df.groupby(["percent_tna", "portno"]).sum()

,,report_dt,security_rank,eff_dt,nbr_shares,market_val,security_name,cusip
percent_tna,portno,,,,,,,
-200.00,3086562,2020/12/31,2,2021/01/08,-8.667746e+07,-1.059169e+08,EUR/USD Forward Contract,0
-199.90,3086604,2020/12/31,2,2021/01/08,-4.889844e+09,-4.736340e+07,JPY/USD Forward Contract,0
-197.20,3087462,2020/11/30,4,2021/01/08,-5.900000e+03,-2.137688e+07,EMINI S&P DEC0,0
-176.40,307545c,2020/11/30,535,2021/01/08,-3.740000e+02,-8.259848e+07,2YR T-NOTES MAR1,0
-173.40,3069606,2020/11/30,660,2021/01/08,-5.910000e+03,-1.305233e+09,2YR T-NOTES MAR1,0
...,...,...,...,...,...,...,...,...
299.85,3086556,2020/12/31,1,2021/01/08,6.097380e+07,6.097380e+07,Other Assets less Liabilities,0
299.94,3086604,2020/12/31,1,2021/01/08,7.105212e+07,7.105212e+07,Other Assets less Liabilities,0
300.01,3086607,2020/12/31,1,2021/01/08,2.904950e+08,2.904950e+08,Other Assets less Liabilities,0
300.04,3086562,2020/12/31,1,2021/01/08,1.588645e+08,1.588645e+08,Other Assets less Liabilities,0
300.08,308655c,2020/12/31,1,2021/01/08,8.666786e+07,8.666786e+07,Other Assets less Liabilities,0

In [19]:
df.groupby(["portno","percent_tna"]).sum()

                                                             report_dt  \
portno  percent_tna
2998623 -0.34                                               2020/11/30
        -0.17                                               2020/11/30
        -0.02                                               2020/11/30
         0.00        2020/11/302020/11/302020/11/302020/11/302020/1...
         0.01        2020/11/302020/11/302020/11/302020/11/302020/1...
...                                                                ...
3092652  0.61                           2020/12/312020/12/312020/12/31
         0.62                                               2020/12/31
         0.63                                               2020/12/31
         3.01                                               2020/12/31
         101.93                                             2020/12/31

                     security_rank  \
portno  percent_tna
2998623 -0.34                  351
        -0.17                  350
        -0.02                  349
         0.00                 6587
         0.01                 2603
...                            ...
3092652  0.61                   18
         0.62                    4
         0.63                    3
         3.01                    2
         101.93                  1

                                                                eff_dt  \
portno  percent_tna
2998623 -0.34                                               2021/01/08
        -0.17                                               2021/01/08
        -0.02                                               2021/01/08
         0.00        2021/01/082021/01/082021/01/082021/01/082021/0...
         0.01        2021/01/082021/01/082021/01/082021/01/082021/0...
...                                                                ...
3092652  0.61                           2021/01/082021/01/082021/01/08
         0.62                                               2021/01/08
         0.63                                               2021/01/08
         3.01                                               2021/01/08
         101.93                                             2021/01/08

                      nbr_shares    market_val  \
portno  percent_tna
2998623 -0.34             -299.0 -4.131339e+07
        -0.17             -167.0 -2.104722e+07
        -0.02         51655800.0 -2.063265e+06
         0.00          2206333.0  2.698138e+06
         0.01          7586000.0  8.187522e+06
...                          ...           ...
3092652  0.61             8280.0  2.415028e+06
         0.62             3864.0  8.125606e+05
         0.63             5382.0  8.339947e+05
         3.01             6760.0  3.968005e+06
         101.93      134422204.0  1.344131e+08

                                                         security_name  \
portno  percent_tna
2998623 -0.34                                         10YR TNotes MAR1
        -0.17                                         5YR T NOTES MAR1
        -0.02                                 Forward General Security
         0.00        Mizuho Fin 3 4.600% 27-Mar-2024Crown Castle In...
         0.01        Energy Transfer Operating LP 4.2% 15-SEP-2023S...
...                                                                ...
3092652  0.61                    MONGODB INCZSCALER INCRINGCENTRAL INC
         0.62                                 CROWDSTRIKE HOLDINGS INC
         0.63                                  PELOTON INTERACTIVE INC
         3.01             Dow Jones US Low Beta Total Return Index TRS
         101.93                                               USD Cash

                                                                 cusip
portno  percent_tna
2998623 -0.34                                                        0
        -0.17                                                        0
        -0.02                                                        0
         0.00        60688UAB22822VAF431282AN69351UAM25272KAR36206B...
         0.01        29278NAC44106MAQ677415CP14309UAA29379VAQ582839...
...                                                                ...
3092652  0.61                                 60937P1098980G1076680R20
         0.62                                                 22788C10
         0.63                                                 70614W10
         3.01                                                        0
         101.93                                                      0

[184136 rows x 7 columns]

In [14]:
df.groupby(["percent_tna", "portno"]).sum().sort_values("percent_tna", ascending=False) #

,,report_dt,security_rank,eff_dt,nbr_shares,market_val,security_name,cusip
percent_tna,portno,,,,,,,
300.08,308655c,2020/12/31,1,2021/01/08,8.666786e+07,8.666786e+07,Other Assets less Liabilities,0
300.04,3086562,2020/12/31,1,2021/01/08,1.588645e+08,1.588645e+08,Other Assets less Liabilities,0
300.01,3086607,2020/12/31,1,2021/01/08,2.904950e+08,2.904950e+08,Other Assets less Liabilities,0
299.94,3086604,2020/12/31,1,2021/01/08,7.105212e+07,7.105212e+07,Other Assets less Liabilities,0
299.85,3086556,2020/12/31,1,2021/01/08,6.097380e+07,6.097380e+07,Other Assets less Liabilities,0
...,...,...,...,...,...,...,...,...
-173.40,3069606,2020/11/30,660,2021/01/08,-5.910000e+03,-1.305233e+09,2YR T-NOTES MAR1,0
-176.40,307545c,2020/11/30,535,2021/01/08,-3.740000e+02,-8.259848e+07,2YR T-NOTES MAR1,0
-197.20,3087462,2020/11/30,4,2021/01/08,-5.900000e+03,-2.137688e+07,EMINI S&P DEC0,0
-199.90,3086604,2020/12/31,2,2021/01/08,-4.889844e+09,-4.736340e+07,JPY/USD Forward Contract,0
-200.00,3086562,2020/12/31,2,2021/01/08,-8.667746e+07,-1.059169e+08,EUR/USD Forward Contract,0

In [15]:
df.groupby(["portno", "percent_tna"]).sum().sort_values("report_dt", ascending=False)

,,report_dt,security_rank,eff_dt,nbr_shares,market_val,security_name,cusip
portno,percent_tna,,,,,,,
3062442,0.00,2020/12/312020/12/312020/12/312020/12/312020/1...,45034325,2021/01/082021/01/082021/01/082021/01/082021/0...,1.136068e+09,1.239098e+09,Freddie Mac 01-JUL-2036 G02252Freddie Mac 01-O...,3128LXQD3132XTPU3140H7ZA31307VG43140HBBW3140H5...
307883d,0.00,2020/12/312020/12/312020/12/312020/12/312020/1...,29593442,2021/01/082021/01/082021/01/082021/01/082021/0...,8.882192e+09,1.026911e+10,International Business Machines Corp 7% 30-OCT...,459200AM71713UAW698299AK20030NAF30161NAC3140J5...
3092256,0.00,2020/12/312020/12/312020/12/312020/12/312020/1...,28376252,2021/01/082021/01/082021/01/082021/01/082021/0...,9.509151e+08,1.078538e+09,International Business Machines Corp 5.875% 29...,459200BB25389JAR042735BG31572UAG056752AK3140Q8...
3062436,0.01,2020/12/312020/12/312020/12/312020/12/312020/1...,14911019,2021/01/082021/01/082021/01/082021/01/082021/0...,1.739651e+09,2.013036e+09,Lear Corp 3.8% 15-SEP-2027Republic Services In...,521865AY760759AS88032WAE41754WAS496902AQ91324P...
3092256,0.01,2020/12/312020/12/312020/12/312020/12/312020/1...,6525902,2021/01/082021/01/082021/01/082021/01/082021/0...,1.756002e+09,2.000681e+09,Caterpillar Financial Services Corp 2.55% 29-N...,14913Q2E4581X0DA023135BF023135AW31418CZ43132A5...
...,...,...,...,...,...,...,...,...
307465b,1.26,2011/04/30,34,2021/01/08,2.289890e+05,1.756117e+07,Nov Inc ORD,62955J10
3077241,1.87,2011/04/30,21,2021/01/08,1.229600e+04,9.429802e+05,Nov Inc ORD,62955J10
307483b,1.87,2011/04/30,20,2021/01/08,1.867900e+04,1.432493e+06,Nov Inc ORD,62955J10
3069018,0.62,2010/12/31,81,2021/01/08,5.470000e+03,3.678575e+05,Nov Inc ORD,62955J10
3073329,2.53,2010/12/31,14,2021/01/08,1.499190e+05,1.008205e+07,Nov Inc ORD,62955J10